# Generated by Django 4.2.13 on 2024-06-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blossom_main', '0002_alter_post_excerpt_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
