# Generated by Django 4.2.13 on 2024-06-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blossom_main', '0002_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
