# Generated by Django 4.2.13 on 2024-06-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blossom_main', '0009_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ready to Publish'), (1, 'Published'), (2, 'Save for Later')], default=0),
        ),
    ]
