# Generated by Django 4.2.13 on 2024-06-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blossom_main', '0012_remove_post_likes_count_post_likes_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='favourites_count',
        ),
    ]
