# Generated by Django 4.2.13 on 2024-06-18 12:56

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('developer', '0004_remove_developerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developerprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='project_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
