# Generated by Django 4.2.13 on 2024-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_alter_developerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='languages',
            field=models.TextField(blank=True),
        ),
    ]
