# Generated by Django 4.2.13 on 2024-06-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_developerprofile_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerprofile',
            name='project_link',
        ),
    ]
