# Generated by Django 4.2.13 on 2024-06-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_remove_developerprofile_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
