# Generated by Django 4.2.13 on 2024-06-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_remove_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerprofile',
            name='certifications',
        ),
    ]
