# Generated by Django 4.2.13 on 2024-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_developer',
            field=models.BooleanField(default=False),
        ),
    ]
